language: ruby
rvm:
- 2.1.3
env:
  global:
  - secure: hNvKhy3BjEXiN93LdJeT2l6FbHkwoZ09MaQYap+7uZ9e0STMV6Tcg1rKzZsVOT0DV7LEE9XlKb42E0g6xZfKP8cw/BXUk+XCsfm5dTjDbDQtH2TmBxgfY3aGRI2AQnkHhR7g/6NWsaghab/Buc1dbyORkd4mQ45f+VbdUlwnbKY=
  - secure: jzureysNKOM6Jtn+HgiuQtrp1Vz/xOY090Sqe9Q/BMLtSC5MAEB1dvRsN0ZFypjNJohzuGpk1kgUD3KKgZW/pC7RzOCxyAMTXVHSA0bVjh2YbQVqwiKO2jydjGTT4NO2UsXjC/mPjdUa0218r9h00cO2nEmL0yeOB+rDmocQHu4=
before_install:
  - openssl aes-256-cbc -k "$SUPER_SECRET_PASSWORD" -in factor-test.pem.enc -out factor-test.pem -d
  - openssl aes-256-cbc -k "$SUPER_SECRET_PASSWORD" -in factor-test-validator.pem.enc -out factor-test-validator.pem -d
deploy:
  provider: rubygems
  gem: factor-connector-chef
  api_key:
    secure: T24epDVon+Cx5yVd02i1ToHjr5pWnMjTCyudzlAXLBF9Rtsta6N6O41RNuHk94KXzoyfS4r8snblzENqR4OFYGE7VkDR1S14nE1rJWM7O9H3ExJh+mPrGtZNQ2Iaxl/a6wGNUb8TQYQEV8v+Qdt7FyFvtESZxHbSClJ7ChOZ1v0=
  on:
    tags: true
    all_branches: true